WANT_HWACCELS=(
#    a64multi5_encoder
#    a64multi_encoder
#    aac_at_encoder
#    aac_encoder
#    aac_mf_encoder
#    ac3_encoder
#    ac3_fixed_encoder
#    ac3_mf_encoder
#    adpcm_adx_encoder
#    adpcm_argo_encoder
#    adpcm_g722_encoder
#    adpcm_g726_encoder
#    adpcm_g726le_encoder
#    adpcm_ima_alp_encoder
#    adpcm_ima_amv_encoder
#    adpcm_ima_apm_encoder
#    adpcm_ima_qt_encoder
#    adpcm_ima_ssi_encoder
#    adpcm_ima_wav_encoder
#    adpcm_ima_ws_encoder
#    adpcm_ms_encoder
#    adpcm_swf_encoder
#    adpcm_yamaha_encoder
#    alac_at_encoder
#    alac_encoder
#    alias_pix_encoder
#    amv_encoder
#    anull_encoder
#    apng_encoder
#    aptx_encoder
#    aptx_hd_encoder
#    ass_encoder
#    asv1_encoder
#    asv2_encoder
#    av1_amf_encoder
#    av1_mediacodec_encoder
#    av1_nvenc_encoder
#    av1_qsv_encoder
#    av1_vaapi_encoder
#    avrp_encoder
#    avui_encoder
#    ayuv_encoder
#    bitpacked_encoder
#    bmp_encoder
#    cfhd_encoder
#    cinepak_encoder
#    cljr_encoder
#    comfortnoise_encoder
#    dca_encoder
#    dfpwm_encoder
#    dnxhd_encoder
#    dpx_encoder
#    dvbsub_encoder
#    dvdsub_encoder
#    dvvideo_encoder
#    eac3_encoder
#    exr_encoder
#    ffv1_encoder
#    ffvhuff_encoder
#    fits_encoder
#    flac_encoder
#    flashsv2_encoder
#    flashsv_encoder
#    flv_encoder
#    g723_1_encoder
#    gif_encoder
#    h261_encoder
#    h263_encoder
#    h263_v4l2m2m_encoder
#    h263p_encoder
#    h264_amf_encoder
#    h264_mediacodec_encoder
#    h264_mf_encoder
#    h264_nvenc_encoder
#    h264_omx_encoder
#    h264_qsv_encoder
#    h264_v4l2m2m_encoder
#    h264_vaapi_encoder
#    h264_videotoolbox_encoder
#    hap_encoder
#    hdr_encoder
#    hevc_amf_encoder
#    hevc_mediacodec_encoder
#    hevc_mf_encoder
#    hevc_nvenc_encoder
#    hevc_qsv_encoder
#    hevc_v4l2m2m_encoder
#    hevc_vaapi_encoder
#    hevc_videotoolbox_encoder
#    huffyuv_encoder
#    ilbc_at_encoder
#    jpeg2000_encoder
#    jpegls_encoder
#    libaom_av1_encoder
#    libcodec2_encoder
#    libfdk_aac_encoder
#    libgsm_encoder
#    libgsm_ms_encoder
#    libilbc_encoder
#    libjxl_encoder
#    libkvazaar_encoder
#    libmp3lame_encoder
#    libopencore_amrnb_encoder
#    libopenh264_encoder
#    libopenjpeg_encoder
#    libopus_encoder
#    librav1e_encoder
#    libshine_encoder
#    libspeex_encoder
#    libsvtav1_encoder
#    libtheora_encoder
#    libtwolame_encoder
#    libvo_amrwbenc_encoder
#    libvorbis_encoder
#    libvpx_vp8_encoder
#    libvpx_vp9_encoder
#    libwebp_anim_encoder
#    libwebp_encoder
#    libx262_encoder
#    libx264_encoder
#    libx264rgb_encoder
#    libx265_encoder
#    libxavs2_encoder
#    libxavs_encoder
#    libxvid_encoder
#    ljpeg_encoder
#    magicyuv_encoder
#    mjpeg_encoder
#    mjpeg_qsv_encoder
#    mjpeg_vaapi_encoder
#    mlp_encoder
#    movtext_encoder
#    mp2_encoder
#    mp2fixed_encoder
#    mp3_mf_encoder
#    mpeg1video_encoder
#    mpeg2_qsv_encoder
#    mpeg2_vaapi_encoder
#    mpeg2video_encoder
#    mpeg4_encoder
#    mpeg4_mediacodec_encoder
#    mpeg4_omx_encoder
#    mpeg4_v4l2m2m_encoder
#    msmpeg4v2_encoder
#    msmpeg4v3_encoder
#    msrle_encoder
#    msvideo1_encoder
#    nellymoser_encoder
#    opus_encoder
#    pam_encoder
#    pbm_encoder
#    pcm_alaw_at_encoder
#    pcm_alaw_encoder
#    pcm_bluray_encoder
#    pcm_dvd_encoder
#    pcm_f32be_encoder
#    pcm_f32le_encoder
#    pcm_f64be_encoder
#    pcm_f64le_encoder
#    pcm_mulaw_at_encoder
#    pcm_mulaw_encoder
#    pcm_s16be_encoder
#    pcm_s16be_planar_encoder
#    pcm_s16le_encoder
#    pcm_s16le_planar_encoder
#    pcm_s24be_encoder
#    pcm_s24daud_encoder
#    pcm_s24le_encoder
#    pcm_s24le_planar_encoder
#    pcm_s32be_encoder
#    pcm_s32le_encoder
#    pcm_s32le_planar_encoder
#    pcm_s64be_encoder
#    pcm_s64le_encoder
#    pcm_s8_encoder
#    pcm_s8_planar_encoder
#    pcm_u16be_encoder
#    pcm_u16le_encoder
#    pcm_u24be_encoder
#    pcm_u24le_encoder
#    pcm_u32be_encoder
#    pcm_u32le_encoder
#    pcm_u8_encoder
#    pcm_vidc_encoder
#    pcx_encoder
#    pfm_encoder
#    pgm_encoder
#    pgmyuv_encoder
#    phm_encoder
#    png_encoder
#    ppm_encoder
#    prores_aw_encoder
#    prores_encoder
#    prores_ks_encoder
#    prores_videotoolbox_encoder
#    qoi_encoder
#    qtrle_encoder
#    r10k_encoder
#    r210_encoder
#    ra_144_encoder
#    rawvideo_encoder
#    roq_dpcm_encoder
#    roq_encoder
#    rpza_encoder
#    rv10_encoder
#    rv20_encoder
#    s302m_encoder
#    sbc_encoder
#    sgi_encoder
#    smc_encoder
#    snow_encoder
#    sonic_encoder
#    sonic_ls_encoder
#    speedhq_encoder
#    srt_encoder
#    ssa_encoder
#    subrip_encoder
#    sunrast_encoder
#    svq1_encoder
#    targa_encoder
#    text_encoder
#    tiff_encoder
#    truehd_encoder
#    tta_encoder
#    ttml_encoder
#    utvideo_encoder
#    v210_encoder
#    v308_encoder
#    v408_encoder
#    v410_encoder
#    vbn_encoder
#    vc2_encoder
#    vnull_encoder
#    vorbis_encoder
#    vp8_mediacodec_encoder
#    vp8_v4l2m2m_encoder
#    vp8_vaapi_encoder
#    vp9_mediacodec_encoder
#    vp9_qsv_encoder
#    vp9_vaapi_encoder
#    wavpack_encoder
#    wbmp_encoder
#    webvtt_encoder
#    wmav1_encoder
#    wmav2_encoder
#    wmv1_encoder
#    wmv2_encoder
#    wrapped_avframe_encoder
#    xbm_encoder
#    xface_encoder
#    xsub_encoder
#    xwd_encoder
#    y41p_encoder
#    yuv4_encoder
#    zlib_encoder
#    zmbv_encoder
)
